# 1. Port và ID định danh
server.port=${PORT:8080}
server.id=${SERVER_ID:Local_Server}

# 2. Cấu hình PostgreSQL (Lấy từ Environment Variables trên Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Link các node
peer.servers=${PEER_SERVERS:}

# 5. Khác
spring.main.allow-bean-definition-overriding=true