# 1. Port và ID định danh
server.port=${PORT:8080}
server.id=${SERVER_ID:Local_Server}

# 2. Cấu hình PostgreSQL 
# LƯU Ý: Phải có chữ "jdbc:" ở đầu dòng url này
spring.datasource.url=jdbc:postgresql://booking_db_fq2h_user:RJ1fp3SncNHfI0AskR9cpLex59roW60t@dpg-d75p1p9r0fns73f8vvkg-a.singapore-postgres.render.com/booking_db_fq2h

# Các thông số đăng nhập
spring.datasource.username=booking_db_fq2h_user
spring.datasource.password=RJ1fp3SncNHfI0AskR9cpLex59roW60t
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Link các node (Sẽ điền trên Render)
peer.servers=${PEER_SERVERS:}

# 5. Cấu hình khác
spring.main.allow-bean-definition-overriding=true